//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityType
    {
        public ActivityType()
        {
            this.JunctionTypeActions = new HashSet<JunctionTypeAction>();
            this.JunctionReportTypes = new HashSet<JunctionReportType>();
        }
    
        public int TypeID { get; set; }
        public string TypeName { get; set; }
        public bool isActive { get; set; }
        public byte[] RecordVersion { get; set; }
    
        public virtual ICollection<JunctionTypeAction> JunctionTypeActions { get; set; }
        public virtual ICollection<JunctionReportType> JunctionReportTypes { get; set; }
    }
}
