//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CommunityAction
    {
        public CommunityAction()
        {
            this.JunctionPopulationActions = new HashSet<JunctionPopulationAction>();
            this.JunctionRoleActions = new HashSet<JunctionRoleAction>();
            this.JunctionDepartmentActions = new HashSet<JunctionDepartmentAction>();
            this.JunctionTypeActions = new HashSet<JunctionTypeAction>();
        }
    
        public int ActionID { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string BreifDescription { get; set; }
        public Nullable<double> Duration { get; set; }
        public int LocationID { get; set; }
        public Nullable<int> ProgramID { get; set; }
        public string SubLocation { get; set; }
        public string Notes { get; set; }
        public string AddedBy { get; set; }
        public byte[] RecordVersion { get; set; }
        public string SubProgram { get; set; }
    
        public virtual Location Location { get; set; }
        public virtual Program Program { get; set; }
        public virtual ICollection<JunctionPopulationAction> JunctionPopulationActions { get; set; }
        public virtual ICollection<JunctionRoleAction> JunctionRoleActions { get; set; }
        public virtual ICollection<JunctionDepartmentAction> JunctionDepartmentActions { get; set; }
        public virtual ICollection<JunctionTypeAction> JunctionTypeActions { get; set; }
    }
}
