//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Department
    {
        public Department()
        {
            this.JunctionDepartmentActions = new HashSet<JunctionDepartmentAction>();
            this.JunctionReportDepartments = new HashSet<JunctionReportDepartment>();
        }
    
        public int DepartmentID { get; set; }
        public string DepartmentName { get; set; }
        public bool isActive { get; set; }
        public byte[] RecordVersion { get; set; }
    
        public virtual ICollection<JunctionDepartmentAction> JunctionDepartmentActions { get; set; }
        public virtual ICollection<JunctionReportDepartment> JunctionReportDepartments { get; set; }
    }
}
