//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Location
    {
        public Location()
        {
            this.CommunityActions = new HashSet<CommunityAction>();
            this.JunctionReportLocations = new HashSet<JunctionReportLocation>();
        }
    
        public int LocationID { get; set; }
        public string LocationName { get; set; }
        public bool isActive { get; set; }
        public byte[] RecordVersion { get; set; }
    
        public virtual ICollection<CommunityAction> CommunityActions { get; set; }
        public virtual ICollection<JunctionReportLocation> JunctionReportLocations { get; set; }
    }
}
