//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Program
    {
        public Program()
        {
            this.CommunityActions = new HashSet<CommunityAction>();
            this.JunctionReportPrograms = new HashSet<JunctionReportProgram>();
        }
    
        public int ProgramID { get; set; }
        public string ProgramName { get; set; }
        public bool isActive { get; set; }
        public byte[] RecordVersion { get; set; }
    
        public virtual ICollection<CommunityAction> CommunityActions { get; set; }
        public virtual ICollection<JunctionReportProgram> JunctionReportPrograms { get; set; }
    }
}
