//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Report
    {
        public Report()
        {
            this.JunctionReportDepartments = new HashSet<JunctionReportDepartment>();
            this.JunctionReportLocations = new HashSet<JunctionReportLocation>();
            this.JunctionReportPopulations = new HashSet<JunctionReportPopulation>();
            this.JunctionReportPrograms = new HashSet<JunctionReportProgram>();
            this.JunctionReportRoles = new HashSet<JunctionReportRole>();
            this.JunctionReportTypes = new HashSet<JunctionReportType>();
        }
    
        public int ReportID { get; set; }
        public string SearchValue { get; set; }
        public bool SortByDate { get; set; }
        public Nullable<System.DateTime> BeginReportDate { get; set; }
        public Nullable<System.DateTime> EndReportDate { get; set; }
        public bool SearchBreifDescription { get; set; }
        public bool SortByDuration { get; set; }
        public Nullable<double> LowDuration { get; set; }
        public Nullable<double> HighDuration { get; set; }
        public bool SortByLocation { get; set; }
        public bool SortByProgram { get; set; }
        public bool SortByDepartment { get; set; }
        public bool SortByPopulation { get; set; }
        public bool SortByRole { get; set; }
        public bool SortByType { get; set; }
        public bool SearchDepartment { get; set; }
        public bool SearchNotes { get; set; }
        public bool SortAddedBy { get; set; }
        public string ReportBy { get; set; }
        public System.DateTime ReportDate { get; set; }
        public byte[] RecordVersion { get; set; }
        public string ReportName { get; set; }
    
        public virtual ICollection<JunctionReportDepartment> JunctionReportDepartments { get; set; }
        public virtual ICollection<JunctionReportLocation> JunctionReportLocations { get; set; }
        public virtual ICollection<JunctionReportPopulation> JunctionReportPopulations { get; set; }
        public virtual ICollection<JunctionReportProgram> JunctionReportPrograms { get; set; }
        public virtual ICollection<JunctionReportRole> JunctionReportRoles { get; set; }
        public virtual ICollection<JunctionReportType> JunctionReportTypes { get; set; }
    }
}
