//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CommunityHealth.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class TargetPopulation
    {
        public TargetPopulation()
        {
            this.JunctionPopulationActions = new HashSet<JunctionPopulationAction>();
            this.JunctionReportPopulations = new HashSet<JunctionReportPopulation>();
        }
    
        public int PopulationID { get; set; }
        public string PopulationName { get; set; }
        public bool isActive { get; set; }
        public byte[] RecordVersion { get; set; }
    
        public virtual ICollection<JunctionPopulationAction> JunctionPopulationActions { get; set; }
        public virtual ICollection<JunctionReportPopulation> JunctionReportPopulations { get; set; }
    }
}
